import type { ExamLevel, RedemittelCategory } from "../model/types";

export const examLevelB1: ExamLevel = {
  id: "b1",
  level: "B1",
  title: "Goethe & ÖSD Zertifikat B1",
  category: "Prüfung",
  description: "Strukturierte Vorbereitung auf das Goethe & ÖSD B1 Zertifikat",
  totalDuration: "ca. 3,5 Stunden",
  passingScore: "60% (60 von 100 Punkten pro Modul)",
  sections: [
    {
      id: "b1-lesen",
      title: "Lesen",
      duration: "65 Minuten",
      points: 100,
      description: "Leseverstehen in verschiedenen Textsorten",
      parts: [
        {
          name: "Teil 1",
          taskType: "Zuordnung (Blog-Texte)",
          items: 6,
          points: 20,
        },
        {
          name: "Teil 2",
          taskType: "Multiple Choice (Artikel)",
          items: 6,
          points: 20,
        },
        {
          name: "Teil 3",
          taskType: "Richtig/Falsch (Anleitungen)",
          items: 7,
          points: 20,
        },
        {
          name: "Teil 4",
          taskType: "Zuordnung (Leserkommentare)",
          items: 7,
          points: 20,
        },
        {
          name: "Teil 5",
          taskType: "Multiple Choice (Anzeigen)",
          items: 4,
          points: 20,
        },
      ],
      tips: [
        "Bestehensgrenze: 60 Punkte (max. 100).",
        "Überschriften und erste Sätze zuerst lesen.",
        "Schlüsselwörter markieren.",
        "Bei Multiple Choice: Ausschlussprinzip nutzen.",
        "Zeit einteilen: ca. 12 Min. pro Teil.",
      ],
    },
    {
      id: "b1-hoeren",
      title: "Hören",
      duration: "40 Minuten",
      points: 100,
      description: "Hörverstehen mit verschiedenen Audioformaten",
      parts: [
        {
          name: "Teil 1",
          taskType: "Richtig/Falsch (Durchsagen)",
          items: 10,
          points: 25,
        },
        {
          name: "Teil 2",
          taskType: "Multiple Choice (Vortrag)",
          items: 5,
          points: 25,
        },
        {
          name: "Teil 3",
          taskType: "Richtig/Falsch (Gespräch)",
          items: 7,
          points: 25,
        },
        {
          name: "Teil 4",
          taskType: "Zuordnung (Diskussion)",
          items: 8,
          points: 25,
        },
      ],
      tips: [
        "Module können einzeln abgelegt werden.",
        "Aufgaben vor dem Hören lesen.",
        "Beim ersten Hören: Hauptidee verstehen.",
        "Beim zweiten Hören: Details prüfen.",
        "Auf Signalwörter achten (aber, trotzdem, deshalb).",
      ],
    },
    {
      id: "b1-schreiben",
      title: "Schreiben",
      duration: "60 Minuten",
      points: 100,
      description: "Persönliche und formelle E-Mails sowie Meinungsäußerung",
      parts: [
        {
          name: "Teil 1",
          taskType: "Informelle E-Mail",
          items: 1,
          points: 40,
          description:
            "ca. 80 Wörter · 3 Inhaltspunkte · Anrede → Einleitung → Inhalt → Schluss",
          checklist: [
            "Anrede",
            "Einleitung",
            "Beschreibung",
            "Begründung (Präsens)",
            "Vorschlag für ein Treffen",
            "Schlusssatz & Gruß",
          ],
        },
        {
          name: "Teil 2",
          taskType: "Diskussionsbeitrag",
          items: 1,
          points: 40,
          description:
            "ca. 80 Wörter · Meinung äußern · Pro- und Kontra-Argumente",
          checklist: [
            "Einleitung",
            "Überleitung",
            "Pro-Argument",
            "Kontra-Argument",
            "Eigene Meinung",
            "Schluss",
          ],
        },
        {
          name: "Teil 3",
          taskType: "Formelle E-Mail",
          items: 1,
          points: 20,
          description:
            "ca. 40 Wörter · Entschuldigung / Absage / Anfrage · Sie-Form",
          checklist: [
            "Formelle Anrede",
            "Grund des Schreibens",
            "Entschuldigung / Bitte",
            "Dank",
            "Formeller Gruß",
          ],
        },
      ],
      tips: [
        "Alle Inhaltspunkte bearbeiten. Jeder fehlende Punkt kostet massiv Punkte!",
        "Schreiben 1: Anrede + Einleitung + alle 3 Punkte + Vorschlag + Schluss.",
        "Schreiben 2: Einleitung → Pro → Kontra → Meinung → Schluss.",
        "Schreiben 3: Sehr kurz halten, aber formell (Sie-Form!).",
      ],
    },
    {
      id: "b1-sprechen",
      title: "Sprechen",
      duration: "15 Minuten (+ 15 Min. Vorbereitung)",
      points: 100,
      description: "Paarprüfung mit drei Teilen",
      parts: [
        {
          name: "Teil 1",
          taskType: "Gemeinsam planen",
          items: 1,
          points: 25,
          description:
            "ca. 3 Min · Gemeinsam etwas besprechen · Vorschläge machen und reagieren",
          checklist: [
            "Einleitung & Einstieg",
            "Vorschläge machen",
            "Zustimmen / Ablehnen",
            "Fragen stellen",
            "Einigung & Schluss",
          ],
        },
        {
          name: "Teil 2",
          taskType: "Präsentation (5 Folien)",
          items: 1,
          points: 50,
          description: "ca. 3 Min · Ein Thema vorstellen · 5-Folien-Struktur",
          checklist: [
            "Folie 1: Thema & Struktur",
            "Folie 2: Erfahrungen",
            "Folie 3: Heimatland",
            "Folie 4: Vor-/Nachteile & Meinung",
            "Folie 5: Dank & Schluss",
          ],
        },
        {
          name: "Teil 3",
          taskType: "Feedback & Frage",
          items: 1,
          points: 25,
          description:
            "ca. 2 Min · Rückmeldung zur Präsentation · Eine Frage stellen",
          checklist: [
            "Rückmeldung geben",
            "Interessante Frage stellen",
            "Auf Fragen antworten",
          ],
        },
      ],
      tips: [
        "Frei sprechen! Augenkontakt halten.",
        "Flüssigkeit: Nicht zu viele Pausen, Füllwörter nutzen.",
        "Interaktion: Auf den Partner reagieren.",
      ],
    },
  ],
};

export const redemittelB1: RedemittelCategory = {
  "Schreiben 1: Informelle E-Mail": [
    {
      label: "1 · Anrede",
      phrases: [
        "Liebe Sandra, / Hallo Sandra,",
        "Lieber Markus, / Hallo Markus,",
        "Liebe Sandra und Markus, / Liebe Sandra, lieber Markus,",
        "Liebe Alle, / Hallo zusammen,",
      ],
    },
    {
      label: "2 · Einleitung",
      phrases: [
        "--- Fragen / Bezug auf Kontakt ---",
        "Wie geht es dir jetzt? Hoffentlich geht es dir schon besser.",
        "Wie geht es dir? Fühlst du dich besser?",
        "Ich hoffe, es geht dir schon besser.",
        "Hoffentlich hattest du viel Spaß auf deiner Reise.",
        "Ich hoffe, dass deine Reise gut war.",
        "Hoffentlich ist die Prüfung gut gelaufen.",
        "Entschuldige, dass ich mich so lange nicht gemeldet habe.",
        "--- Einleitung zum Thema ---",
        "Endlich schreibe ich dir. Ich möchte dir von meinem Erlebnis erzählen.",
        "Wie du ja weißt, vor einer Woche habe ich meinen Geburtstag gefeiert. Schade, dass du nicht kommen konntest.",
        "Ohne dich war es nicht so lustig. / Ohne dich war der Geburtstag nicht so schön.",
        "Letztes Wochenende hatten wir die Abschlussparty und haben dich sehr vermisst.",
        "Ich habe etwas Tolles erlebt und möchte es dir unbedingt erzählen!",
      ],
    },
    {
      label: "3 · Beschreibung",
      phrases: [
        "--- Party / Feier (Perfekt) ---",
        "Es war eine tolle Atmosphäre! Die Stimmung war großartig – alle hatten viel Spaß.",
        "Wir waren ungefähr [Zahl] Leute / Personen.",
        "Wir haben gegrillt und leckere Gerichte gegessen. Es gab Salat, Fleisch und Süßigkeiten.",
        "Eine Band hat gespielt und wir haben getanzt. / Es gab tolle Musik und wir haben viel getanzt.",
        "Aktivitäten: tanzen – singen – neue Leute kennenlernen – Spiele spielen",
        "Ich habe [Name] kennengelernt. Er/Sie ist sehr nett und interessant.",
        "Gefühle: Das war wunderschön! / Das hat mir wirklich gut gefallen! / Das war unvergesslich!",
        "--- Ausflug / Reise (Perfekt) ---",
        "Das Wetter war herrlich – die Sonne hat geschienen und es war warm.",
        "Wir waren den ganzen Tag / das ganze Wochenende unterwegs.",
        "Ich war mit meiner Familie / mit Freunden / mit meiner Klasse da.",
        "Verkehrsmittel: mit dem Zug – mit dem Rad – mit dem Bus – zu Fuß – mit dem Auto",
        "Wir haben gegrillt / ein Picknick gemacht / lokale Spezialitäten probiert.",
        "Aktivitäten: wandern – Sehenswürdigkeiten besichtigen – schwimmen – klettern – Lagerfeuer machen – Fotos machen",
        "Wir haben in einem Zelt / einer Jugendherberge / einer Pension übernachtet.",
        "Gefühle: Das war lustig. / Das war ganz nett. / Das war fantastisch! / Das werde ich nie vergessen!",
        "--- Neues Auto (Präsens) ---",
        "Modell: Es ist ein BMW / Mercedes / Sportwagen / Geländewagen / Familienkombi.",
        "Farbe: Es ist grau / silber / schwarz / weiß / blau.",
        "Ausstattung: Es ist groß und komfortabel / kompakt und sparsam. Es hat ein Navigationssystem und starke Lautsprecher.",
        "Preis: Es war zwar gebraucht, aber in sehr gutem Zustand und hat [Preis] gekostet.",
        "Gefühle: Ich bin so glücklich! / Es ist ein Traum! / Ich fahre es sehr gerne!",
        "--- Neue Wohnung (Präsens) ---",
        "Lage: Sie liegt im Zentrum / in der Nähe des Bahnhofs / am Stadtrand / in einem ruhigen Viertel.",
        "Stil: modern und hell / Altbau mit viel Charme.",
        "Größe: Sie hat [Zahl] Quadratmeter und [Zahl] Zimmer, eine Küche und ein Bad.",
        "Nachbarn: Die Nachbarn sind sehr freundlich und ruhig.",
        "In der Nähe gibt es viele Einkaufsmöglichkeiten und gute Verkehrsverbindungen. Der Bus hält direkt vor der Tür.",
        "Gefühle: Ich bin sehr zufrieden! / Ich fühle mich hier wie zu Hause. / Es ist meine Traumwohnung!",
      ],
    },
    {
      label: "4 · Begründung (Präsens)",
      badge: "Präsens",
      phrases: [
        "Ich fand …, weil / denn …",
        "… war besonders toll, deshalb / daher …",
        "Besonders gut gefallen hat mir …, weil …",
        "Am besten hat mir … gefallen, denn …",
        "Die größte Attraction war …, weil …",
      ],
    },
    {
      label: "5 · Vorschlag für ein Treffen",
      phrases: [
        "--- Strukturen ---",
        "Könnten wir uns bald treffen?",
        "Wollen wir uns am [Tag] treffen?",
        "Komm doch mich besuchen! / Lass uns doch bald treffen!",
        "Könntest du mich am Wochenende besuchen?",
        "Wie wäre es, wenn wir uns am [Tag] im [Ort] treffen?",
        "Hast du am Samstagnachmittag Zeit? Dann könnten wir zusammen ins Kino gehen.",
        "Hast du Lust, … zu …?",
        "--- Wann / Wo / Grund ---",
        "Wann: am Samstagnachmittag – am Freitagabend – morgen Abend – nächste Woche",
        "Wo: im Café – ins Kino – ins Theater – zu mir nach Hause – im Park",
        "Grund: Dann zeige ich dir die Fotos / das neue Auto / die neue Wohnung.",
        "Grund: Dann erzähle ich dir mehr von der Party / der Reise / dem Ausflug.",
        "Grund: Dann lernst du meine neue Freundin / meinen neuen Freund kennen.",
      ],
    },
    {
      label: "6 · Schlusssatz & Gruß",
      phrases: [
        "Schreib zurück! / Antworte schnell! / Ich warte auf deine Antwort!",
        "Ich warte auf deine E-Mail / deinen Anruf.",
        "Melde dich! / Ruf mich an! / Schick mir eine Nachricht!",
        "Liebe Grüße, [Vorname]",
        "Viele liebe Grüße und bis bald!",
      ],
    },
  ],
  "Schreiben 2: Diskussionsbeitrag": [
    {
      label: "1 · Einleitung (Keine Anrede!)",
      phrases: [
        'Das Thema „……" finde ich sehr wichtig / interessant / aktuell, deshalb möchte ich meine Meinung dazu äußern.',
        'In der letzten Zeit wird viel über „……" diskutiert. Deshalb möchte ich meine Meinung dazu sagen.',
        'Die Sendung / Der Artikel „……" war wirklich interessant und hat mich zum Nachdenken gebracht.',
        "Wie … finde ich es schade / gut, dass …",
        "Ich stimme …s Meinung (nicht) zu, weil …",
        "Im Gegensatz zu … bin ich der Meinung, dass …",
        "Also, ich bin auch [Beruf/Situation] und möchte meine Meinung zu diesem Thema äußern.",
      ],
    },
    {
      label: "2 · Argumente & Überleitung",
      phrases: [
        "--- Einräumen / Gegenüberstellung ---",
        "Zwar …, aber …",
        "Natürlich …, aber …",
        "Einerseits …, andererseits …",
        "Auf der einen Seite …, auf der anderen Seite …",
        "Es stimmt zwar, dass …, aber trotzdem …",
        "Obwohl … ist, glaube ich, dass …",
        "--- Ergänzen / Betonen ---",
        "Außerdem … / Hinzu kommt, …",
        "Darüber hinaus …",
        "Besonders wichtig ist, dass …",
        '„……" hat einen positiven / negativen Einfluss auf …',
        "Es ist sinnvoll / sinnlos / wichtig, … zu verbieten / erlauben.",
        "Viele Studien haben gezeigt, dass …",
      ],
    },
    {
      label: "3 · Meinung & Schlusssatz",
      phrases: [
        "Ich denke, dass … / Ich glaube, dass … / Ich finde, dass …",
        "Ich bin der Meinung / der Ansicht, dass …",
        "Meiner Meinung nach sollte man …",

        // Deutsch Lernen - High-Performance React Architecture

        "Ich vertrete folgenden Standpunkt: …",
        "Aus diesen Gründen bin ich der Meinung, dass …",
        "Zusammenfassend lässt sich sagen, dass …",
        "Deshalb / Daher bin ich (nicht) dafür / dagegen.",
        "Eine gute Lösung wäre …, denn damit könnte man …",
      ],
    },
    {
      label: "4 · Musterlösungen (Beispieltexte)",
      phrases: [
        "--- Muster 1: Haustiere ---",
        "Das Thema „Haustiere“ finde ich sehr interessant, deshalb möchte ich meine Meinung dazu äußern. Haustiere können zwar sehr schmutzig und laut sein. Aber sie sind ein treuer Begleiter des Menschen und können sehr lustig und unterhaltsam sein. Viele Studien haben gezeigt, dass Haustiere eine gute Lösung gegen Einsamkeit sein können – besonders für alte Menschen. Außerdem können Haustiere sehr nützlich sein, indem sie behinderten Menschen helfen und Häuser bewachen. Aus diesen Gründen bin ich der Meinung, dass Haustiere sehr nützlich sind.",
        "--- Muster 2: Soziale Netzwerke ---",
        "Das Thema „Soziale Netzwerke“ ist sehr aktuell, deshalb möchte ich meine Meinung dazu äußern. Soziale Netzwerke verbinden zwar Menschen aus aller Welt und helfen, Kontakt mit Freunden zu pflegen. Aber sie machen auch abhängig und verschwenden viel Zeit. In sozialen Netzwerken sind persönliche Daten außerdem nicht immer gut geschützt, was gefährlich sein kann. Meiner Meinung nach sollte man soziale Netzwerke nur in Maßen benutzen – zum Beispiel eine Stunde pro Tag.",
        "--- Muster 3: Fremdsprachen ---",
        "Das Thema „Fremdsprachen im Kindergarten“ finde ich sehr wichtig. Einerseits lernen Kinder Fremdsprachen schneller und besser als Erwachsene. Fremdsprachen sind außerdem wichtig für das spätere Berufsleben. Andererseits brauchen Kinder Zeit zum Spielen – sie sollten nicht nur lernen. Hinzu kommt, dass Kinder zuerst ihre Muttersprache beherrschen sollten. Trotzdem bin ich dafür, denn spielerisches Fremdsprachenlernen macht Spaß und ist sehr effektiv.",
        "--- Muster 4: Flexible Arbeitszeiten ---",
        "Das Thema „Feste Arbeitszeiten“ ist sehr aktuell. Ich habe im Fernsehen eine Diskussion darüber gesehen und möchte meine Meinung sagen. Feste Arbeitszeiten schaffen zwar Ordnung und erleichtern die Planung. Aber flexible Arbeitszeiten sind für Familien mit Kindern viel praktischer. Außerdem arbeiten Menschen besser, wenn sie selbst entscheiden können, wann sie produktiv sind. Meiner Meinung nach sollten Firmen flexible Arbeitszeiten anbieten, damit Mitarbeiter zufriedener und produktiver sind.",
      ],
    },
  ],
  "Schreiben 3: Formelle E-Mail": [
    {
      label: "1 · Anrede",
      phrases: [
        "Sehr geehrte Frau [Nachname],",
        "Sehr geehrter Herr [Nachname],",
        "Sehr geehrte Damen und Herren,",
      ],
    },
    {
      label: "2 · Einleitung & Absage",
      phrases: [
        "Vielen Dank für Ihre Einladung / Ihre E-Mail / Ihr Angebot.",
        "Ich schreibe Ihnen, weil ich Sie informieren möchte, dass …",
        "Mit großem Interesse habe ich Ihre Stellenausschreibung / Ihr Angebot gelesen.",
        "Ich wende mich an Sie, weil ich ein Problem / eine Frage habe.",
        "--- Entschuldigung / Absage ---",
        "Es tut mir leid, aber ich kann zu … leider nicht kommen.",
        "Entschuldigen Sie bitte, aber ich kann zu … nicht kommen.",
        "Leider muss ich mich entschuldigen, da ich zu … nicht kommen kann.",
        "Leider bin ich an diesem Tag verhindert.",
        "Zu meinem Bedauern kann ich an … nicht teilnehmen.",
      ],
    },
    {
      label: "3 · Gründe für das Fehlen",
      phrases: [
        "Mein Vater / meine Mutter ist sehr krank und ich muss ihn/sie ins Krankenhaus fahren.",
        "Ich habe mich verletzt und muss zu Hause bleiben.",
        "Ich leide unter einer starken Erkältung und hohem Fieber. Der Arzt meinte, ich soll im Bett bleiben.",
        "Ich muss wegen eines wichtigen Gesprächs verreisen.",
        "Ich habe einen Termin mit einem wichtigen Kunden, der großes Interesse an unseren Produkten hat.",
        "Ich habe leider gleichzeitig einen anderen, sehr wichtigen Termin.",
      ],
    },
    {
      label: "4 · Bitte & Schlusssatz",
      phrases: [
        "Könnten wir vielleicht den Termin auf die nächste Woche / morgen verschieben?",
        "Ich wäre Ihnen sehr dankbar, wenn wir einen neuen Termin vereinbaren könnten.",
        "Ich freue mich auf Ihre Antwort. / Ich warte auf Ihre Rückmeldung.",
        "Vielen Dank für Ihr Verständnis. / Vielen Dank im Voraus.",
        "Mit freundlichen Grüßen, [Vorname Nachname]",
        "--- Musterlösung: Termin absagen ---",
        "Sehr geehrter Herr Melder, ich schreibe Ihnen, weil ich zum Gespräch über meine Karriere leider nicht kommen kann. Ich habe einen Termin mit einem wichtigen Kunden, der großes Interesse an unseren Produkten hat. Könnten wir den Termin vielleicht auf morgen verschieben? Vielen Dank im Voraus. Mit freundlichen Grüßen, [Name]",
      ],
    },
  ],
  "Sprechen 1: Gemeinsame Planung": [
    {
      label: "1 · Einleitung & Einstieg",
      phrases: [
        "Wie du ja weißt, am Wochenende wollen wir mit den anderen Teilnehmern unseres Deutschkurses einen Museumsbesuch machen und das müssen wir planen.",
        "Wie du ja weißt, unser Nachbar hat sich das Bein gebrochen. Er kann seine Wohnung nicht verlassen und wir möchten ihm helfen.",
        "Wir wollen mit unserer Familie am Sonntag einen Ausflug machen und das müssen wir gemeinsam planen.",
        "Hast du darüber nachgedacht? / Hast du ein paar Vorschläge? / Hast du ein paar Ideen?",
        "Ja, ich habe mir schon ein paar Notizen gemacht. / Ja, ich habe ein paar interessante Vorschläge.",
      ],
    },
    {
      label: "2 · Fragen stellen",
      phrases: [
        "Welches Museum / Welchen Ort könnten wir besuchen?",
        "Wann könnten / wollen wir hingehen? / Um wie viel Uhr wollen wir losfahren?",
        "Wie könnten wir hinfahren? / Womit fahren wir? / Nehmen wir den Bus oder das Auto?",
        "Was könnten wir dort unternehmen? / Was sollen wir mitbringen?",
        "Was könnten wir anziehen? Welche Kleidung passt dazu?",
        "Wen könnten wir noch einladen? / Wer kann mitkommen?",
        "Wie könnten wir unserem Nachbarn helfen? / Was könnten wir für ihn tun?",
        "Was sollen wir als Geschenk mitbringen? / Wie viel wollen wir ausgeben?",
      ],
    },
    {
      label: "3 · Vorschläge machen",
      phrases: [
        "Ich schlage vor, … zu + Infinitiv.",
        "Wollen / Sollen wir …?",
        "Wir könnten … Das wäre gut, weil …",
        "Ich würde gerne … Was hältst du davon?",
        "Wie wäre es, wenn wir …? Das finde ich praktischer / günstiger / schöner.",
        "Was hältst du davon, wenn wir …?",
        "Vielleicht könnten wir … Was denkst du? / Wie findest du das? / Bist du einverstanden?",
      ],
    },
    {
      label: "4 · Zustimmen",
      phrases: [
        "Ja, das ist eine gute Idee! / Das klingt super! / Das ist prima!",
        "Ja, das passt mir. / Das gefällt mir sehr!",
        "Ja, gern – warum nicht?",
        "In Ordnung! / Ich bin einverstanden. / Ok, das klingt gut.",
        "Das ist großartig! / Wunderbar!",
      ],
    },
    {
      label: "5 · Ablehnen / Gegenvorschlag",
      phrases: [
        "Das klingt gut, aber da kann ich nicht, denn ich habe …",
        "Das hört sich gut an, aber ich würde lieber …, weil das … ist.",
        "Das finde ich nicht so gut. Es wäre besser, wenn …",
        "Das ist zwar gut, aber wir könnten auch …, das ist billiger / praktischer.",
        "Hm, ich weiß nicht … Das könnte zu teuer / zu weit sein. Vielleicht sollten wir lieber …",
        "Das ist leider nicht möglich, weil … Aber wie wäre es mit …?",
      ],
    },
    {
      label: "6 · Einigung & Schluss",
      phrases: [
        "Richtig, das machen wir! / Damit bin ich einverstanden!",
        "Du hast recht. Das machen wir so. / Ja, deine Idee ist besser.",
        "Dann ist alles klar! / Ich denke, wir haben alles geplant.",
        "Das wird bestimmt eine großartige Party / ein toller Ausflug!",
        "Super, ich bin schon gespannt! Bis Samstag!",
        "--- Übergänge ---",
        "Zuerst … / Dann … / Außerdem brauchen wir … / Jetzt fehlt nur noch …",
        "Etwas zum Essen und Trinken brauchen wir auch. Hast du eine Idee?",
      ],
    },
  ],
  "Sprechen 2: Präsentation": [
    {
      label: "Folie 1 – Thema & Struktur",
      phrases: [
        'Guten Tag, meine Damen und Herren. Heute möchte ich über das Thema „…" sprechen. Zuerst beginne ich mit meinen persönlichen Erfahrungen. Dann werde ich von der Situation in meinem Heimatland berichten. Danach nenne ich die Vor- und Nachteile und äußere meine Meinung. Schließlich komme ich zum Dank.',
        'Über das Thema „…" wird heute viel diskutiert. Mein Vortrag besteht aus folgenden Teilen: persönliche Erfahrungen, Situation in Marokko, Vor- und Nachteile und meine Meinung.',
        'Ich habe das Thema „…" gewählt, denn es interessiert mich sehr und ist sehr aktuell.',
      ],
    },
    {
      label: "Folie 2 – Erfahrungen",
      phrases: [
        "Als ich Kind war, … / Als ich in die Schule ging, …",
        "Ich persönlich … / In meiner Familie … / Bei uns zu Hause …",
        "Letztes Jahr … / Im letzten Sommer … / Am letzten Wochenende …",
        "Meine Erfahrungen mit diesem Thema sind … Zum Beispiel …",
        "Ich erinnere mich gut daran, als … Das hat mich sehr beeindruckt.",
        "Gefühle: Das war toll! / Das hat Spaß gemacht! / Das hat mir sehr geholfen.",
      ],
    },
    {
      label: "Folie 3 – Heimatland",
      phrases: [
        "In den letzten Jahren hat sich die Situation in Marokko sehr verändert …",
        "Die Situation in Marokko lässt sich so beschreiben: …",
        "Bei uns in Marokko ist die Situation folgendermaßen: … Zum Beispiel …",
        "In Marokko ist [Thema] sehr verbreitet / kaum bekannt / sehr wichtig / ein großes Problem.",
        "Im Vergleich zu Deutschland / Österreich / der Schweiz ist es bei uns …",
        "Ein gutes Beispiel dafür ist …",
      ],
    },
    {
      label: "Folie 4 – Vor-/Nachteile & Meinung",
      phrases: [
        "--- Vor- und Nachteile ---",
        "Ein wichtiger Vorteil ist: … / Ein großer Nachteil ist: …",
        "Zwar …, aber … / Obwohl …, …",
        "Einerseits …, andererseits …",
        "Außerdem … / Hinzu kommt: …",
        "--- Meinung äußern ---",
        "Ich bin der Meinung, dass … / Meiner Meinung nach …",
        "Aus den genannten Gründen bin ich der Meinung, dass …",
        "Ich glaube / Ich denke / Ich finde, dass … Deshalb bin ich dafür / dagegen.",
      ],
    },
    {
      label: "Folie 5 – Dank & Schluss",
      phrases: [
        "Das wollte ich Ihnen erklären. Herzlichen Dank für Ihre Aufmerksamkeit.",
        "Damit bin ich am Ende meiner Präsentation angekommen. Vielen Dank fürs Zuhören.",
        "Ich hoffe, ich konnte Ihnen klar machen, wie ich über dieses Thema denke. Danke, dass Sie mir zugehört haben.",
        "Ich würde mich über Ihre Fragen sehr freuen. / Ich beantworte gerne Ihre Fragen.",
      ],
    },
  ],
  "Sprechen 3: Rückmeldung & Frage": [
    {
      label: "Rückmeldung geben",
      phrases: [
        "Danke für Ihre / deine Präsentation. Sie war sehr interessant / informativ / überzeugend.",
        'Dein Vortrag hat mir gut gefallen. Die Informationen über „…" fand ich besonders interessant.',
        "Ich fand deinen Punkt über … sehr überzeugend / interessant.",
        "Du hast einige gute Argumente genannt. Ich teile deine Meinung, dass …",
      ],
    },
    {
      label: "Frage stellen",
      phrases: [
        "Aber ich hätte dazu noch eine Frage.",
        "Könntest du mir noch erklären, warum …?",
        "Könntest du die Vorteile / Nachteile / deine Meinung noch einmal kurz wiederholen?",
        "Was denkst du über …? / Wie findest du …? ",
        "Darf ich dich noch etwas fragen? Wie ist die Situation in deiner Familie / Stadt bezüglich …?",
      ],
    },
  ],
  "Wortschatz: Konnektoren": [
    {
      label: "Kausal (Grund)",
      phrases: [
        "weil: … weil ich krank bin. (Verb am Ende)",
        "denn: Ich komme nicht, denn ich bin krank. (Hauptsatz)",
        "deshalb / daher: Ich bin krank, deshalb komme ich nicht.",
        "da: Da ich krank bin, komme ich nicht.",
        "aus diesem Grund: Aus diesem Grund bin ich dagegen.",
      ],
    },
    {
      label: "Konzessiv (Einräumung)",
      phrases: [
        "obwohl: Obwohl es teuer ist, kaufe ich es.",
        "trotzdem: Es ist teuer, trotzdem kaufe ich es.",
        "zwar … aber: Es ist zwar teuer, aber gut.",
        "dennoch: Das ist schwierig, dennoch versuche ich es.",
      ],
    },
    {
      label: "Adversativ (Gegensatz)",
      phrases: [
        "aber: Das ist gut, aber teuer.",
        "jedoch: Das ist praktisch, jedoch auch gefährlich.",
        "hingegen: Er ist aktiv, sie hingegen ist ruhig.",
        "im Gegensatz dazu: Im Gegensatz dazu bin ich dafür.",
      ],
    },
    {
      label: "Additiv (Ergänzung)",
      phrases: [
        "und: Es ist gesund und praktisch.",
        "außerdem: Außerdem ist es sehr günstig.",
        "hinzu kommt: Hinzu kommt, dass es umweltfreundlich ist.",
        "darüber hinaus: Darüber hinaus spart man Zeit.",
        "nicht nur … sondern auch: Es ist nicht nur billig, sondern auch praktisch.",
      ],
    },
    {
      label: "Temporal / Konditional",
      phrases: [
        "als: Als ich Kind war, … (einmalig, Vergangenheit)",
        "wenn: Wenn ich müde bin, schlafe ich früh. / Wenn man Sport treibt, bleibt man fit.",
        "nachdem: Nachdem ich gegessen habe, …",
        "bevor: Bevor ich schlafe, lese ich.",
        "während: Während er arbeitet, koche ich.",
        "falls: Falls du Zeit hast, komm vorbei.",
        "damit: Ich lerne, damit ich die Prüfung bestehe.",
        "um … zu: Ich gehe ins Gym, um fit zu bleiben.",
      ],
    },
    {
      label: "Folge / Ergebnis",
      phrases: [
        "sodass: Es regnet stark, sodass wir nass werden.",
        "deshalb: Es ist kalt. Deshalb bleibe ich zu Hause.",
        "indem: Man kann helfen, indem man spendet.",
      ],
    },
  ],
  "Wortschatz: Zeitausdrücke": [
    {
      label: "Vergangenheit (Schreiben 1 / Sprechen 2)",
      phrases: [
        "vor einer Woche / vor einem Monat / vor einem Jahr",
        "letztes Wochenende / letzten Samstag / letzte Woche",
        "im letzten Sommer / im letzten Urlaub / letztes Jahr",
        "gestern / vorgestern / am Wochenende",
        "als ich Kind / Schüler / Student war",
      ],
    },
    {
      label: "Zukunft / Vorschläge",
      phrases: [
        "nächste Woche / nächsten Samstag / nächsten Monat",
        "am Samstagnachmittag / am Freitagabend / morgen Abend",
        "in einer Woche / in zwei Tagen / bald",
        "am Nachmittag / am Abend / am Wochenende",
      ],
    },
    {
      label: "Zeit gewinnen / Abwechslung",
      phrases: [
        "Also … / Ähm … / Moment mal …",
        "Wie sagt man …? / Ich meine …",
        "Das heißt … / Das bedeutet … / Mit anderen Worten …",
        "Zum Beispiel … / Zum Beispiel kann man …",
        "Besonders … / Vor allem … / Insbesondere …",
        "Heutzutage … / In der heutigen Zeit … / Immer mehr …",
        "Im Allgemeinen … / In der Regel …",
      ],
    },
  ],
  "Wortschatz: Prüfungsthemen": [
    {
      label: "Arbeit",
      phrases: [
        "--- Ausbildung ---",
        "Pro: Ausbildung gibt jungen Menschen einen sicheren Berufseinstieg. Man verdient schon während der Ausbildung Geld. Man bekommt praktische Erfahrung direkt im Betrieb. Eine abgeschlossene Ausbildung öffnet viele Türen auf dem Arbeitsmarkt.",
        "Kontra: Azubis verdienen oft sehr wenig – kaum genug zum Leben. In manchen Betrieben werden Azubis ausgenutzt. Ein Studium bietet oft bessere Karrierechancen und ein höheres Gehalt.",
        "--- Berufswahl ---",
        "Pro: Die freie Berufswahl ist ein wichtiges Recht – jeder sollte den Beruf wählen, der zu ihm passt. Wenn man einen Beruf liebt, arbeitet man motivierter und erfolgreicher. Eltern und Schule sollten Jugendliche bei der Berufswahl beraten und unterstützen.",
        "Kontra: Viele Jugendliche wählen einen Beruf ohne realistische Vorstellung vom Alltag. Manche Berufe sind sehr beliebt, aber bieten wenige Stellen – z.B. Schauspieler oder Sportler. Gesellschaftlicher Druck zwingt manche Jugendliche in Berufe, die sie nicht mögen.",
        "--- Studenten und Arbeit in den Ferien ---",
        "Pro: Ferienjobs geben Studenten praktische Erfahrung und Einblick in die Arbeitswelt. Man verdient Geld und wird finanziell unabhängiger von den Eltern. Ein Nebenjob verbessert den Lebenslauf und zeigt Engagement und Eigeninitiative.",
        "Kontra: Studenten sollten die Ferien zum Erholen und Lernen nutzen – nicht zum Arbeiten. Zu viel Arbeit neben dem Studium kann die Noten und die Gesundheit schädigen. Schlecht bezahlte Ferienjobs werden oft ausgenutzt.",
        "--- Teilzeitarbeit ---",
        "Pro: Teilzeitarbeit ist ideal für Eltern mit kleinen Kindern, die Beruf und Familie vereinbaren möchten. Man hat mehr Zeit für Hobbys, Familie und Gesundheit. Teilzeitarbeit kann Stress reduzieren und die Lebensqualität verbessern.",
        "Kontra: Teilzeitkräfte verdienen weniger und haben oft weniger Rentenansprüche. In vielen Berufen ist Teilzeit nicht möglich oder wird nicht akzeptiert. Teilzeitkräfte werden manchmal nicht so ernst genommen wie Vollzeitkräfte.",
      ],
    },
    {
      label: "Gesellschaft",
      phrases: [
        "--- Auslandsaufenthalt ---",
        "Pro: Man lernt eine neue Sprache viel schneller, wenn man im Land lebt. Man entdeckt neue Kulturen, Menschen und Lebensweisen. Ein Auslandsaufenthalt macht selbstständiger und selbstbewusster. Er verbessert die Chancen auf dem Arbeitsmarkt erheblich.",
        "Kontra: Ein Auslandsaufenthalt kostet viel Geld. Man vermisst Familie und Freunde – Heimweh ist sehr belastend. Die Anpassung an eine neue Kultur und Sprache ist oft schwierig.",
        "--- Freundschaft ---",
        "Pro: Echte Freundschaft ist eines der wichtigsten Dinge im Leben – Freunde helfen uns in schwierigen Zeiten. Freunde machen das Leben schöner, lustiger und erfüllter. Durch Freundschaft lernt man Kompromisse, Rücksicht und Empathie.",
        "Kontra: Echte Freundschaft ist selten – viele Bekanntschaften nennen sich Freundschaft, sind es aber nicht. Freundschaften können zerbrechen und großen emotionalen Schmerz verursachen. In sozialen Netzwerken hat man viele Kontakte, aber kaum echte Freunde.",
        "--- Musik im Zeitalter des Internets ---",
        "Pro: Dank des Internets hat man Zugang zu Millionen Songs – überall und jederzeit. Streaming-Dienste sind günstig und praktisch. Künstler können ihre Musik ohne Plattenfirma direkt veröffentlichen.",
        "Kontra: Musiker verdienen durch Streaming kaum Geld – das schadet der Musikbranche. Illegale Downloads zerstören die Einnahmen der Künstler. CDs und Schallplatten haben einen besonderen Klang und Wert, der verloren geht.",
      ],
    },
    {
      label: "Freizeit",
      phrases: [
        "--- Kinos sterben ---",
        "Pro: Kinos bieten ein einzigartiges Erlebnis – große Leinwand, guter Ton, gemeinsames Schauen. Ins Kino gehen ist ein beliebtes Freizeitvergnügen und soziales Erlebnis. Kinos unterstützen die Filmindustrie und lokale Wirtschaft.",
        "Kontra: Streaming-Dienste wie Netflix machen Kinos weniger attraktiv – man sieht Filme bequem zu Hause. Kinotickets sind sehr teuer. Viele junge Menschen bevorzugen Serien und Online-Inhalte gegenüber Kinofilmen.",
      ],
    },
    {
      label: "Bildung",
      phrases: [
        "--- Sprachenlernen ---",
        "Pro: Wer mehrere Sprachen spricht, hat deutlich bessere Chancen im Berufsleben. Sprachenlernen öffnet Türen zu neuen Kulturen und Menschen. Studien zeigen, dass Mehrsprachigkeit das Gehirn trainiert und vor Alzheimer schützen kann.",
        "Kontra: Sprachenlernen ist zeitaufwendig und anstrengend – es braucht viel Geduld. Guter Sprachunterricht kostet Geld – Sprachkurse und Nachhilfe sind teuer. Nicht jeder hat das Talent oder die Zeit, eine neue Sprache zu lernen.",
        "--- Sprachenlernen mit dem Internet ---",
        "Pro: Online-Sprachkurse sind günstiger und flexibler als traditionelle Kurse – man lernt im eigenen Tempo. Es gibt viele kostenlose Ressourcen: YouTube, Apps, Podcasts und Online-Tandempartner. Man kann mit Muttersprachlern weltweit in Kontakt treten und üben.",
        "Kontra: Online fehlt der direkte Kontakt zu einem Lehrer – Fehler werden nicht sofort korrigiert. Ohne Disziplin und Motivation gibt man leicht auf. Echte Konversation und Aussprache lassen sich online schlechter üben als im Präsenzkurs.",
      ],
    },
  ],
};
