import { ExamLevel, RedemittelData } from "../model/types";

export const examLevels: ExamLevel[] = [
  {
    id: "b1",
    level: "B1",
    title: "Goethe-Zertifikat B1",
    category: "Prüfung",
    description: "Selbstständige Sprachverwendung – Mittelstufe",
    totalDuration: "ca. 3,5 Stunden",
    passingScore: "60% (60 von 100 Punkten pro Modul)",
    sections: [
      {
        id: "b1-lesen",
        title: "Lesen",
        duration: "65 Minuten",
        points: 100,
        description: "Leseverstehen in verschiedenen Textsorten",
        parts: [
          {
            name: "Teil 1",
            taskType: "Zuordnung (Blog-Texte)",
            items: 6,
            points: 20,
          },
          {
            name: "Teil 2",
            taskType: "Multiple Choice (Artikel)",
            items: 6,
            points: 20,
          },
          {
            name: "Teil 3",
            taskType: "Richtig/Falsch (Anleitungen)",
            items: 7,
            points: 20,
          },
          {
            name: "Teil 4",
            taskType: "Zuordnung (Leserkommentare)",
            items: 7,
            points: 20,
          },
          {
            name: "Teil 5",
            taskType: "Multiple Choice (Anzeigen)",
            items: 4,
            points: 20,
          },
        ],
        tips: [
          "Bestehensgrenze: 60 Punkte (max. 100).",
          "Überschriften und erste Sätze zuerst lesen.",
          "Schlüsselwörter markieren.",
          "Bei Multiple Choice: Ausschlussprinzip nutzen.",
          "Zeit einteilen: ca. 12 Min. pro Teil.",
        ],
      },
      {
        id: "b1-hoeren",
        title: "Hören",
        duration: "40 Minuten",
        points: 100,
        description: "Hörverstehen mit verschiedenen Audioformaten",
        parts: [
          {
            name: "Teil 1",
            taskType: "Richtig/Falsch (Durchsagen)",
            items: 10,
            points: 25,
          },
          {
            name: "Teil 2",
            taskType: "Multiple Choice (Vortrag)",
            items: 5,
            points: 25,
          },
          {
            name: "Teil 3",
            taskType: "Richtig/Falsch (Gespräch)",
            items: 7,
            points: 25,
          },
          {
            name: "Teil 4",
            taskType: "Zuordnung (Diskussion)",
            items: 8,
            points: 25,
          },
        ],
        tips: [
          "Module können einzeln abgelegt werden.",
          "Aufgaben vor dem Hören lesen.",
          "Beim ersten Hören: Hauptidee verstehen.",
          "Beim zweiten Hören: Details prüfen.",
          "Auf Signalwörter achten (aber, trotzdem, deshalb).",
        ],
      },
      {
        id: "b1-schreiben",
        title: "Schreiben",
        duration: "60 Minuten",
        points: 100,
        description: "Persönliche und formelle E-Mails sowie Meinungsäußerung",
        parts: [
          {
            name: "Teil 1",
            taskType: "Informelle E-Mail (~80 Wörter)",
            items: 1,
            points: 40,
          },
          {
            name: "Teil 2",
            taskType: "Diskussionsbeitrag (~80 Wörter)",
            items: 1,
            points: 40,
          },
          {
            name: "Teil 3",
            taskType: "Formelle E-Mail (~40 Wörter)",
            items: 1,
            points: 20,
          },
        ],
        tips: [
          "Alle Inhaltspunkte bearbeiten. Jeder fehlende Punkt kostet massiv Punkte!",
          "Schreiben 1: Anrede + Einleitung + alle 3 Punkte + Vorschlag + Schluss.",
          "Schreiben 2: Einleitung → Pro → Kontra → Meinung → Schluss.",
          "Schreiben 3: Sehr kurz halten, aber formell (Sie-Form!).",
          "Zeit für Korrektur einplanen (5-10 Min.).",
        ],
      },
      {
        id: "b1-sprechen",
        title: "Sprechen",
        duration: "15 Minuten (+ 15 Min. Vorbereitung)",
        points: 100,
        description: "Paarprüfung mit drei Teilen",
        parts: [
          {
            name: "Teil 1",
            taskType: "Gemeinsam planen (~3 Min)",
            items: 1,
            points: 25,
          },
          {
            name: "Teil 2",
            taskType: "Präsentation (5 Folien, ~3 Min)",
            items: 1,
            points: 50,
          },
          {
            name: "Teil 3",
            taskType: "Feedback & Frage (~2 Min)",
            items: 1,
            points: 25,
          },
        ],
        tips: [
          "Aussprache & Intonation: Klar und langsam sprechen.",
          "Flüssigkeit: Nicht zu viele Pausen, Füllwörter nutzen (Also, Ich meine...).",
          "Interaktion: Auf den Partner reagieren, Fragen stellen.",
          "Präsentation: Frei sprechen! Augenkontakt halten.",
        ],
      },
    ],
  },
  {
    id: "b2",
    level: "B2",
    title: "Goethe-Zertifikat B2",
    category: "Prüfung",
    description: "Selbstständige Sprachverwendung – Obere Mittelstufe",
    totalDuration: "ca. 4 Stunden",
    passingScore: "60% (180 von 300 Punkten)",
    sections: [
      {
        id: "b2-lesen",
        title: "Lesen",
        duration: "65 Minuten",
        points: 75,
        description: "Komplexere Texte verstehen und analysieren",
        parts: [
          {
            name: "Teil 1",
            taskType: "Multiple Choice (Sachtext)",
            items: 9,
            points: 9,
          },
          {
            name: "Teil 2",
            taskType: "Zuordnung (Zeitungsartikel)",
            items: 6,
            points: 6,
          },
          {
            name: "Teil 3",
            taskType: "Lückentext (Grammatik im Kontext)",
            items: 6,
            points: 6,
          },
          {
            name: "Teil 4",
            taskType: "Multiple Choice (Kommentare)",
            items: 6,
            points: 6,
          },
          {
            name: "Teil 5",
            taskType: "Wortschatz im Kontext",
            items: 3,
            points: 3,
          },
        ],
        tips: [
          "Komplexe Satzstrukturen analysieren",
          "Textsorte erkennen (Bericht, Kommentar, Interview)",
          "Implizite Informationen verstehen",
          "Synonyme und Umschreibungen erkennen",
        ],
      },
      {
        id: "b2-hoeren",
        title: "Hören",
        duration: "40 Minuten",
        points: 75,
        description: "Anspruchsvolle Hörtexte verstehen",
        parts: [
          {
            name: "Teil 1",
            taskType: "Zuordnung (Aussagen)",
            items: 5,
            points: 10,
          },
          {
            name: "Teil 2",
            taskType: "Multiple Choice (Interview)",
            items: 6,
            points: 12,
          },
          {
            name: "Teil 3",
            taskType: "Richtig/Falsch (Diskussion)",
            items: 6,
            points: 12,
          },
          {
            name: "Teil 4",
            taskType: "Multiple Choice (Vortrag)",
            items: 8,
            points: 16,
          },
        ],
        tips: [
          "Auf Sprecherabsicht achten",
          "Argumentationsstruktur verfolgen",
          "Meinungen von Fakten unterscheiden",
          "Ironie und Untertöne erkennen",
        ],
      },
      {
        id: "b2-schreiben",
        title: "Schreiben",
        duration: "75 Minuten",
        points: 75,
        description: "Formelle Texte und argumentative Beiträge",
        parts: [
          {
            name: "Aufgabe 1",
            taskType: "Forumsbeitrag (Argumentation)",
            items: 1,
            points: 50,
          },
          {
            name: "Aufgabe 2",
            taskType: "Formelle Nachricht (Beschwerde/Anfrage)",
            items: 1,
            points: 25,
          },
        ],
        tips: [
          "Klare Struktur: Einleitung, Hauptteil, Schluss",
          "These, Argument, Beispiel, Schlussfolgerung",
          "Komplexe Satzstrukturen verwenden",
          "Formellen Stil bei Aufgabe 2 beachten",
        ],
      },
      {
        id: "b2-sprechen",
        title: "Sprechen",
        duration: "15 Minuten (+ 15 Min. Vorbereitung)",
        points: 75,
        description: "Paarprüfung: Präsentation und Diskussion",
        parts: [
          {
            name: "Teil 1",
            taskType: "Präsentation (Thema mit Pro/Contra)",
            items: 1,
            points: 25,
          },
          {
            name: "Teil 2",
            taskType: "Diskussion mit Partner",
            items: 1,
            points: 25,
          },
        ],
        tips: [
          "Strukturiert argumentieren",
          "Auf Gegenargumente eingehen",
          "Redemittel für Diskussion nutzen",
          "Flüssig und zusammenhängend sprechen",
        ],
      },
    ],
  },
];

export const redemittelData: RedemittelData = {
  b1: {
    "Schreiben 1: Einleitung": [
      "Wie geht es dir jetzt? Hoffentlich geht es dir schon besser.",
      "Entschuldige, dass ich mich so lange nicht gemeldet habe.",
      "Endlich schreibe ich dir. Ich möchte dir von meinem Erlebnis erzählen.",
      "Wie du ja weißt, vor einer Woche habe ich meinen Geburtstag gefeiert. Schade, dass du nicht kommen konntest.",
      "Ohne dich war es nicht so lustig. / Ohne dich war der Geburtstag nicht so schön.",
      "Ich habe etwas Tolles erlebt und möchte es dir unbedingt erzählen!",
    ],
    "Schreiben 1: Beschreibung (Party/Reise)": [
      "Es war eine tolle Atmosphäre! Die Stimmung war großartig.",
      "Wir haben gegrillt und leckere Gerichte gegessen.",
      "Das Wetter war herrlich – die Sonne hat geschienen.",
      "Verkehrsmittel: mit dem Zug – mit dem Rad – mit dem Bus – zu Fuß.",
      "Aktivitäten: tanzen, neue Leute kennenlernen, Sehenswürdigkeiten besichtigen.",
      "Gefühle: Das war unvergesslich! / Das hat mir wirklich gut gefallen!",
    ],
    "Schreiben 1: Begründung": [
      "Ich fand ..., weil / denn ...",
      "Besonders gut gefallen hat mir ..., weil ...",
      "Am besten hat mir ... gefallen, denn ...",
      "Die größte Attraktion war ..., weil ...",
    ],
    "Schreiben 1: Vorschlag & Schluss": [
      "Könnten wir uns bald treffen?",
      "Wie wäre es, wenn wir uns am Samstag treffen?",
      "Hast du am Samstagnachmittag Zeit? Dann könnten wir zusammen ins Kino gehen.",
      "Schreib zurück! Ich warte auf deine Antwort.",
      "Viele liebe Grüße und bis bald!",
    ],
    "Schreiben 2: Diskussionsbeitrag": [
      "Das Thema „...“ finde ich sehr wichtig / aktuell, deshalb möchte ich meine Meinung dazu äußern.",
      "Meiner Meinung nach sollte man...",
      "Einerseits ..., andererseits ... / Zwar ..., aber ...",
      "Ich stimme ...s Meinung (nicht) zu, weil...",
      "Zusammenfassend lässt sich sagen, dass...",
      "Eine gute Lösung wäre ..., denn damit könnte man ...",
    ],
    "Schreiben 3: Formelle E-Mail": [
      "Sehr geehrte Damen und Herren,",
      "Sehr geehrte(r) Frau/Herr [Name],",
      "Vielen Dank für Ihre Einladung.",
      "Es tut mir leid, aber ich kann zu ... leider nicht kommen.",
      "Ich wäre Ihnen dankbar, wenn wir einen neuen Termin vereinbaren könnten.",
      "Vielen Dank im Voraus. / Mit freundlichen Grüßen,",
    ],
    "Sprechen 1: Gemeinsam planen": [
      "Wir müssen gemeinsam planen, wie wir...",
      "Hast du ein paar Vorschläge oder Ideen?",
      "Ich schlage vor, dass wir...",
      "Was hältst du davon, wenn wir...?",
      "Ja, das ist eine gute Idee! / Das klingt super!",
      "Das ist leider nicht möglich, weil... Aber wie wäre es mit...?",
    ],
    "Sprechen 2: Präsentation Struktur": [
      "Folie 1: Thema & Struktur - Guten Tag, heute möchte ich über ... sprechen. Zuerst ... dann ... schließlich ...",
      "Folie 2: Eigene Erfahrungen - Als ich Kind war ... / In meiner Familie ... / Letztes Jahr ...",
      "Folie 3: Heimatland - Bei uns in Marokko ist die Situation folgendermaßen: ...",
      "Folie 4: Pro/Contra & Meinung - Ein Vorteil ist ... / Ein Nachteil ist ... / Meiner Meinung nach ...",
      "Folie 5: Abschluss & Dank - Herzlichen Dank für Ihre Aufmerksamkeit. Haben Sie noch Fragen?",
    ],
    "Sprechen 3: Rückmeldung & Frage": [
      "Deine Präsentation war sehr interessant / informativ.",
      "Was ich besonders gut fand, war dein Punkt über...",
      "Dazu hätte ich noch eine Frage: Könntest du mir erklären, warum / wie ...?",
      "Wie ist die Situation in deiner Familie / Stadt bezüglich ...?",
    ],
    "Wortschatz: Konnektoren": [
      "Kausal: weil (Nebensatz), denn (Hauptsatz), deshalb/daher (Inversion).",
      "Konzessiv: obwohl (Nebensatz), trotzdem (Inversion), zwar ... aber.",
      "Adversativ: aber, jedoch, hingegen, im Gegensatz dazu.",
      "Additiv: und, außerdem, hinzu kommt, nicht nur ... sondern auch.",
      "Temporal: als (einmalig, Vergangen), wenn (wiederholt/Gegenwart), nachdem, bevor.",
      "Konditional: wenn, falls, damit, um ... zu.",
    ],
    "Wortschatz: Zeitausdrücke": [
      "Vergangenheit: vor einer Woche, letztes Wochenende, im letzten Sommer, gestern.",
      "Zukunft: nächste Woche, am Samstagnachmittag, in zwei Tagen, bald.",
      "Füllwörter: Also ..., Ähm ..., Moment mal ..., Ich meine ..., Das heißt ...",
      "Abwechslung: Besonders ..., Vor allem ..., Im Allgemeinen ..., Heutzutage ...",
    ],
  },
  b2: {
    einleitung: [
      'Das Thema "..." ist heutzutage von großer Bedeutung.',
      "Immer mehr Menschen beschäftigen sich mit der Frage,...",
      "In meinem Beitrag möchte ich die Frage diskutieren, ob...",
    ],
    argumentation: [
      "Einerseits... andererseits...",
      "Dafür/Dagegen spricht, dass...",
      "Ein weiteres Argument ist...",
      "Hinzu kommt, dass...",
      "Man darf nicht vergessen, dass...",
    ],
    beispiel: [
      "Das zeigt sich zum Beispiel daran, dass...",
      "Ein gutes Beispiel dafür ist...",
      "Dies kann man an folgendem Beispiel verdeutlichen:...",
    ],
    schluss: [
      "Zusammenfassend lässt sich sagen, dass...",
      "Abschließend möchte ich betonen, dass...",
      "Alles in allem bin ich der Meinung, dass...",
    ],
    diskussion: [
      "Was meinst du dazu?",
      "Ich verstehe deinen Standpunkt, aber...",
      "Das ist ein interessanter Punkt, jedoch...",
      "Könntest du das näher erläutern?",
    ],
  },
};
