import type { Thema } from "../model/types";

export const themenData: Thema[] = [
  {
    id: "veg",
    label: "Vegetarisch essen",
    cat: "essen",
    pro: [
      "Vegetarisch essen ist gesund – man schützt sich vor Krankheiten wie Krebs und Diabetes.",
      "Man ist immer fit und bleibt schlank.",
      "Tiere haben auch das Recht auf Leben.",
      "Vegane / vegetarische Ernährung ist umweltfreundlicher.",
    ],
    con: [
      "Der Körper braucht Eiweiß und wichtige Nährstoffe, die oft in Fleisch vorkommen.",
      "Fleisch spielt eine große Rolle in der Ernährung, besonders bei Kindern.",
      "Vegetarisches Essen schmeckt manchen nicht und macht nicht immer satt.",
    ],
    text: undefined,
  },
  {
    id: "fast",
    label: "Fast Food",
    cat: "essen",
    pro: [
      "Fast Food schmeckt gut und spart Zeit.",
      "Fast Food ist preiswert – gut für Menschen mit wenig Geld oder Zeit.",
      "Man kann es leicht bestellen – zu Hause oder im Büro.",
    ],
    con: [
      "Fast Food ist ungesund und verursacht Krankheiten wie Diabetes und Herzprobleme.",
      "Fast Food macht dick und faul.",
      "Man weiß oft nicht, woraus es besteht – viele Zusatzstoffe.",
    ],
    text: undefined,
  },
  {
    id: "fertig",
    label: "Fertigessen",
    cat: "essen",
    pro: [
      "Wenn man Fertigessen isst, spart man Zeit. Man kann es schnell in der Mikrowelle aufwärmen.",
      "Fertigessen ist preiswert und praktisch.",
    ],
    con: [
      "Fertigessen ist ungesund und verursacht viele Krankheiten.",
      "Fertigessen macht dick und faul.",
      "Man weiß nicht, woraus es besteht – viele ungesunde Zutaten.",
    ],
    text: undefined,
  },
  {
    id: "bio",
    label: "Bio-Lebensmittel",
    cat: "essen",
    pro: [
      "Bio-Lebensmittel sind gesünder – keine Pestizide oder Chemikalien.",
      "Bio-Produkte sind umweltfreundlicher und schützen die Natur.",
      "Sie schmecken oft besser als normale Produkte.",
      "Man unterstützt lokale Bauern.",
    ],
    con: [
      "Bio-Lebensmittel sind viel teurer als normale Produkte.",
      "Es ist schwierig zu überprüfen, ob Produkte wirklich bio sind.",
      "Nicht jeder kann sich Bio-Lebensmittel leisten.",
    ],
    text: undefined,
  },
  {
    id: "vleisch",
    label: "Sollen wir weniger Fleisch essen?",
    cat: "essen",
    pro: [
      "Weniger Fleisch essen ist gut für die Gesundheit und reduziert das Krebsrisiko.",
      "Die Fleischindustrie ist einer der größten Klimasündiger – weniger Fleisch schützt die Umwelt.",
      "Tiere werden in der Massentierhaltung schlecht behandelt.",
    ],
    con: [
      "Fleisch ist eine wichtige Eiweißquelle, besonders für Kinder und Sportler.",
      "In vielen Kulturen und Familien ist Fleischessen eine wichtige Tradition.",
      "Ohne Fleisch kann es zu Nährstoffmangel kommen.",
    ],
    text: undefined,
  },
  {
    id: "social",
    label: "Soziale Netzwerke / Facebook",
    cat: "tech",
    pro: [
      "Soziale Netzwerke verbinden Menschen aus der ganzen Welt.",
      "Sie sind ein gutes Mittel, um Kontakt mit Familie und Freunden zu pflegen.",
      "Man kann andere Kulturen entdecken und ist immer informiert.",
      "Man kann soziale Netzwerke für Werbung und Karriere nutzen.",
    ],
    con: [
      "Soziale Netzwerke machen einsam und faul – Depressionen und Übergewicht können entstehen.",
      "In sozialen Netzwerken sind persönliche Daten nicht immer geschützt.",
      "Man wird abhängig und verschwendet viel Zeit.",
    ],
    text: undefined,
  },
  {
    id: "inet",
    label: "Informationen aus dem Internet glauben?",
    cat: "tech",
    pro: [
      "Das Internet bietet eine riesige Menge an Informationen – schnell und kostenlos zugänglich.",
      "Es ist bequem und einfach – man findet schnell Antworten.",
      "Es gibt viele zuverlässige Quellen wie Universitäten und Zeitungen.",
    ],
    con: [
      "Informationen aus dem Internet sind nicht immer wahr – viele Fake News.",
      "Man muss viel suchen, um echte Informationen zu finden.",
      "Jeder kann Informationen veröffentlichen, ohne Experte zu sein.",
    ],
    text: undefined,
  },
  {
    id: "liebe",
    label: "Große Liebe im Internet finden?",
    cat: "tech",
    pro: [
      "Das Internet bietet die Möglichkeit, viele Leute kennenzulernen.",
      "Es ist bequem – es gibt viele Partnervermittlungsseiten.",
      "Man kann schon vorher Fotos sehen und eine erste Idee bekommen.",
    ],
    con: [
      "Es kann gefährlich sein – im Internet gibt es viele Betrüger.",
      "Man weiß nicht, mit wem man schreibt.",
      "Persönliche Daten können missbraucht werden.",
      "Virtuelle Liebe kann die reale Liebe nicht ersetzen.",
    ],
    text: undefined,
  },
  {
    id: "buch",
    label: "Gedrucktes Buch vs. E-Book",
    cat: "tech",
    pro: [
      "Gedrucktes Buch: Gut für die Augen, kein Strom nötig, schönes Lesegefühl.",
      "E-Book: Preiswert, praktisch – man kann viele Bücher auf einem Gerät speichern.",
      "E-Book: Man kann neue Bücher sofort kaufen, auch aus dem Ausland.",
    ],
    con: [
      "Gedrucktes Buch: Schwer und teuer – Papier ist umweltfeindlich.",
      "E-Book: Braucht Strom, alte Bücher gibt es oft nicht digital, kann kaputtgehen.",
    ],
    text: undefined,
  },
  {
    id: "einkauf",
    label: "Einkaufen im Internet",
    cat: "tech",
    pro: [
      "Einkaufen im Internet ist schnell, bequem, einfach und oft günstiger.",
      "Das Angebot ist groß und vielfältig – viele Sonderangebote.",
      "Man spart Zeit und Energie und kann Waren aus dem Ausland bestellen.",
    ],
    con: [
      "Einkaufen im Internet kann gefährlich sein – persönliche Daten sind nicht immer geschützt.",
      "Die Produkte können schlechter sein als auf den Fotos.",
      "Man kann die Produkte nicht ausprobieren oder testen.",
      "Die Lieferung kann sich verzögern. Reklamationen sind schwierig.",
    ],
    text: undefined,
  },
  {
    id: "handy",
    label: "Brauchen Kinder ein Handy?",
    cat: "tech",
    pro: [
      "Mit einem Handy ist das Kind immer erreichbar – wichtig bei Notfällen.",
      "Mit dem Handy kann man nicht nur telefonieren, sondern auch lernen und recherchieren.",
      "Heutzutage bilden Schüler Lerngruppen über WhatsApp.",
    ],
    con: [
      "Handynutzung kostet viel Zeit und Geld.",
      "Kann den Augen schaden, Schulleistung verschlechtern und süchtig machen.",
      "Handys können gefährlich sein – viele kinderfeindliche Inhalte im Internet.",
    ],
    text: undefined,
  },
  {
    id: "ki",
    label: "Künstliche Intelligenz (KI)",
    cat: "tech",
    pro: [
      "Künstliche Intelligenz kann bei der Arbeit helfen und Zeit sparen.",
      "KI kann in der Medizin Leben retten – bessere Diagnosen.",
      "KI kann in der Schule personalisiertes Lernen ermöglichen.",
    ],
    con: [
      "KI kann Arbeitsplätze vernichten.",
      "KI kann missbraucht werden – Fake News, Überwachung.",
      "Daten, die für KI genutzt werden, sind oft nicht geschützt.",
    ],
    text: undefined,
  },
  {
    id: "marke",
    label: "Brauchen wir Markenkleidung?",
    cat: "gesellschaft",
    pro: [
      "Markenkleidung hat gute Qualität, hält lange und sieht sehr gut aus.",
      "Wenn man Markenkleidung trägt, fühlt man sich selbstbewusster.",
      "Markenkleidung ist oft modern und trendy.",
    ],
    con: [
      "Markenkleidung ist sehr teuer und kann süchtig machen.",
      "Markenkleidung ist oft nur Marketing – man zahlt für das Logo.",
      "Man sollte Geld nicht für Status ausgeben.",
    ],
    text: undefined,
  },
  {
    id: "second",
    label: "Second-Hand-Kleidung",
    cat: "gesellschaft",
    pro: [
      "Second-Hand-Kleidung ist billig – man kann sogar Markenkleidung günstig finden.",
      "Second-Hand-Kleidung ist eine gute Lösung für Menschen mit wenig Geld.",
      "Second-Hand-Kleidung ist umweltfreundlich – weniger Abfall.",
    ],
    con: [
      "Second-Hand-Kleidung kann Krankheiten und Allergien übertragen.",
      "Sie sieht oft nicht gut aus und man findet nicht alle Größen.",
      "Not immer vorrätig.",
    ],
    text: undefined,
  },
  {
    id: "kleidkind",
    label: "Sollen Eltern bestimmen, was Kinder anziehen?",
    cat: "gesellschaft",
    pro: [
      "Die Eltern wissen besser, what for their children is suitable.",
      "Die Eltern achten besser auf den Preis und die Qualität.",
    ],
    con: [
      "Wenn Kinder ihre Kleidung selbst wählen, entwickelt sich ihre Persönlichkeit besser.",
      "Sie werden selbstbewusster und selbstständiger.",
      "Kinder wissen, was in Mode ist und möchten dazugehören.",
    ],
    text: undefined,
  },
  {
    id: "uniform",
    label: "Schuluniform",
    cat: "bildung",
    pro: [
      "Schuluniform schafft Gleichheit – keine Unterschiede zwischen armen und reichen Schülern.",
      "Die eigene Kleidung bleibt sauber und in gutem Zustand.",
      "Schuluniform sorgt für mehr Ordnung und Konzentration.",
    ],
    con: [
      "Die Schüler möchten ihre Individualität und Freiheit behalten.",
      "Es hat keinen Sinn, Kleidung nur für die Schule zu kaufen – sehr teuer.",
      "In einer Demokratie sollte Kleidung frei wählbar sein.",
    ],
    text: undefined,
  },
  {
    id: "computer",
    label: "Computer in jedem Kursraum?",
    cat: "bildung",
    pro: [
      "Ein Computer in jedem Kursraum erleichtert den Unterricht und macht ihn interessanter.",
      "Mit dem Computer kann man lernen, präsentieren und im Internet recherchieren.",
      "Die Schüler lernen den Umgang mit dem Computer – das hilft im Berufsleben.",
    ],
    con: [
      "Ein Computer in jedem Kursraum kostet viel Geld.",
      "Computer können faul und passiv machen.",
      "Man kann sich nicht immer auf die Technik verlassen.",
      "Ablenkung durch Internet und Spiele.",
    ],
    text: undefined,
  },
  {
    id: "fremd",
    label: "Fremdsprachen im Kindergarten?",
    cat: "bildung",
    pro: [
      "Kinder lernen Fremdsprachen schneller und besser als Erwachsene.",
      "Fremdsprachen sind wichtig im Berufsleben.",
      "Wenn man eine neue Sprache lernt, entdeckt man eine neue Kultur.",
      "Fremdsprachenlernen erhöht nachweislich die Intelligenz.",
    ],
    con: [
      "Kinder sollte ihre Kindheit leben und nicht nur lernen.",
      "Kinder brauchen Zeit zum Spielen.",
      "Kinder sollten zuerst ihre Muttersprache beherrschen.",
    ],
    text: undefined,
  },
  {
    id: "englisch",
    label: "Sollen alle Englisch lernen?",
    cat: "bildung",
    pro: [
      "Englisch ist eine weltweite Sprache der Wissenschaft und Technik.",
      "Die meisten Fachbücher und Websites sind auf Englisch.",
      "Englisch verbindet Menschen aus verschiedenen Kulturen.",
      "Mit Englisch hat man bessere Chancen im Berufsleben.",
    ],
    con: [
      "Eine neue Fremdsprache zu lernen ist nicht immer einfach.",
      "Viele Forscher meinen, dass Chinesisch die Sprache der Zukunft ist.",
      "Andere Sprachen und Kulturen werden dadurch vernachlässigt.",
    ],
    text: undefined,
  },
  {
    id: "privschule",
    label: "Privatschulen vs. staatliche Schulen",
    cat: "bildung",
    pro: [
      "Privatschulen haben oft bessere Ausstattung und kleinere Klassen.",
      "Privatschulen bieten zusätzliche Angebote wie Sport, Musik und Sprachen.",
      "Höhere Qualität der Lehrer und des Unterrichts.",
    ],
    con: [
      "Privatschulen sind sehr teuer – nicht jeder kann sie sich leisten.",
      "Sie fördern soziale Ungleichheit.",
      "Staatliche Schulen sind kostenlos und für alle zugänglich.",
    ],
    text: undefined,
  },
  {
    id: "ausland",
    label: "Studium im Ausland",
    cat: "bildung",
    pro: [
      "Man lernt neue Kulturen, Sprachen und Menschen kennen.",
      "Auslandserfahrung verbessert die Chancen auf dem Arbeitsmarkt.",
      "Man wird selbstständiger und reifer.",
    ],
    con: [
      "Studium im Ausland ist teuer – Studiengebühren und Lebenshaltungskosten.",
      "Man ist weit weg von Familie und Freunden.",
      "Sprach- und Kulturbarrieren können schwierig sein.",
    ],
    text: undefined,
  },
  {
    id: "sprachkurs",
    label: "Online-Sprachkurs vs. Präsenzkurs",
    cat: "bildung",
    pro: [
      "Online: kostenlos oder günstig, bequem von zu Hause, flexibel.",
      "Präsenzkurs: Man lernt Grammatik und Wortschatz schneller, Lehrer kann direkt helfen.",
      "Online: Man kann im eigenen Tempo lernen.",
    ],
    con: [
      "Online: Man kann keine direkten Fragen stellen, keine echte Konversation.",
      "Präsenzkurs: Kann teuer sein und feste Zeiten haben.",
    ],
    text: undefined,
  },
  {
    id: "haustier",
    label: "Haustiere",
    cat: "gesellschaft",
    pro: [
      "Haustiere sind treu und unterhaltsam.",
      "Haustiere helfen behinderten und blinden Menschen.",
      "Haustiere sind eine gute Lösung gegen Einsamkeit.",
      "Kinder lernen durch ein Haustier mehr Verantwortung.",
    ],
    con: [
      "Haustiere haben viele Bedürfnisse – man muss sie füttern, pflegen und Gassi gehen.",
      "Haustiere kosten Geld (Tierarzt, Futter, Zubehör).",
      "Wenn man ein Haustier hat, kann man nicht einfach Urlaub machen.",
    ],
    text: undefined,
  },
  {
    id: "zoo",
    label: "Tiere im Zoo",
    cat: "gesellschaft",
    pro: [
      "Zoos schützen bedrohte Tierarten.",
      "Kinder können im Zoo viel über Tiere lernen.",
      "Zoos betreiben wichtige Forschung für den Tierschutz.",
    ],
    con: [
      "Tiere gehören in die Natur, nicht in den Zoo.",
      "Zootiere leben in zu kleinen, unnatürlichen Gehegen.",
      "Es wäre sinnvoller, natürliche Lebensräume zu schützen.",
    ],
    text: undefined,
  },
  {
    id: "sport",
    label: "Wie viel Sport ist gesund?",
    cat: "gesundheit",
    pro: [
      "Regelmäßiger Sport ist gesund und notwendig – alle Ärzte raten dazu.",
      "Sport baut Stress ab und macht glücklich.",
      "3–4-mal pro Woche, 1–2 Stunden ist ideal.",
    ],
    con: [
      "Zu viel Sport ist schädlich – der Körper braucht Erholung.",
      "Zu wenig Sport führt zu Übergewicht und Faulheit.",
      "Man darf seinen Körper auf keinen Fall überfordern.",
    ],
    text: undefined,
  },
  {
    id: "extrem",
    label: "Extremsport",
    cat: "gesundheit",
    pro: [
      "Extremsport baut Stress ab und ist ein Adrenalinkick.",
      "Man fühlt sich frei und geht an seine Grenzen.",
      "Extremsport hilft, Ängste zu überwinden.",
    ],
    con: [
      "Extremsport ist sehr gefährlich und kann zu schweren Verletzungen führen.",
      "Man gefährdet seinen Körper und manchmal sein Leben.",
      "Extremsport ist meistens sehr teuer.",
    ],
    text: undefined,
  },
  {
    id: "makeup",
    label: "Make-up?",
    cat: "gesundheit",
    pro: [
      "Make-up macht hübscher und attraktiver.",
      "Make-up gibt ein Gefühl von Selbstbewusstsein.",
      "Make-up deckt Makel und man fühlt sich sicherer.",
    ],
    con: [
      "Make-up schadet der Haut bei regelmäßigem Gebrauch.",
      "Es kostet viel Zeit und Geld.",
      "Viele Studien zeigen, dass Make-up süchtig machen kann.",
    ],
    text: undefined,
  },
  {
    id: "schoen",
    label: "Schönheitsoperationen",
    cat: "gesundheit",
    pro: [
      "Mit Schönheitsoperationen sieht man jünger und attraktiver aus.",
      "Sie können Makel abdecken und das Selbstbewusstsein stärken.",
    ],
    con: [
      "Schönheitsoperationen können schlimme Risiken und Komplikationen haben.",
      "Ärzte können Fehler machen und das ist nicht rückgängig zu machen.",
      "Es gibt natürliche Alternativen: Sport, gesunde Ernährung, Naturkosmetik.",
    ],
    text: undefined,
  },
  {
    id: "tattoo",
    label: "Tattoos und Piercing",
    cat: "gesellschaft",
    pro: [
      "Tattoos und Piercing sehen cool aus und sind in Mode.",
      "Sie können an besondere Personen oder Ereignisse erinnern.",
      "Sie sind ein Symbol der Freiheit und Persönlichkeit.",
    ],
    con: [
      "Sie können der Gesundheit schaden (Infektionen, Hautkrebs).",
      "Man kann Tattoos nicht leicht entfernen – mit dem Alter sehen sie nicht mehr gut aus.",
      "Manche Arbeitgeber sehen Tattoos negativ.",
    ],
    text: undefined,
  },
  {
    id: "mama",
    label: "Hotel Mama?",
    cat: "gesellschaft",
    pro: [
      "Man spart Geld und muss nicht selbst kochen und putzen.",
      "Bei Mama gibt es jeden Tag gesundes Essen.",
      "Man kann sich besser auf das Studium konzentrieren.",
      "Man genießt die Gesellschaft der Familie.",
    ],
    con: [
      "Man hat wenig Freiheit und kaum Privatsphäre.",
      "Man wird faul und unselbstständig.",
      "Wenn man allein wohnt, lernt man mehr Verantwortung und Selbstständigkeit.",
    ],
    text: undefined,
  },
  {
    id: "gross",
    label: "Großeltern als Kinderbetreuung?",
    cat: "gesellschaft",
    pro: [
      "Großeltern haben große Erfahrung in der Erziehung und sind geduldig.",
      "Großeltern freuen sich, Zeit mit den Enkeln zu verbringen.",
      "Großeltern sind oft kostenlos und liebevoll.",
      "Kinder können viel von Großeltern lernen.",
    ],
    con: [
      "Großeltern können das Elterngefühl nicht ersetzen.",
      "Großeltern verwöhnen die Kinder und halten sich nicht immer an Regeln.",
      "Großeltern brauchen auch Ruhe und haben vielleicht nicht die Kraft dazu.",
    ],
    text: undefined,
  },
  {
    id: "schlaf",
    label: "Mittagsschlaf in Firmen?",
    cat: "arbeit",
    pro: [

// Deutsch Lernen - High-Performance React Architecture

      "Mitarbeiter fühlen sich nach dem Mittagsschlaf besser und arbeiten produktiver.",
      "Studien belegen, dass Mittagsschlaf Mitarbeiter kreativer und konzentrierter macht.",
      "Die Arbeitsatmosphäre wird entspannter und angenehmer.",
    ],
    con: [
      "Mittagsschlaf kostet wertvolle Arbeitszeit.",
      "Nach einem Mittagsschlaf kann es schwer sein, sich zu konzentrieren.",
      "Nicht alle Mitarbeiter können oder wollen schlafen.",
    ],
    text: undefined,
  },
  {
    id: "homeoffice",
    label: "Homeoffice / Arbeit von zu Hause",
    cat: "arbeit",
    pro: [
      "Man spart Zeit und Geld durch weniger Pendeln.",
      "Man kann flexibler arbeiten und hat mehr Zeit für die Familie.",
      "Weniger Ablenkung durch Kollegen – oft produktiver.",
      "Umweltfreundlicher – weniger Autofahrten.",
    ],
    con: [
      "Man kann sich zu Hause schlechter konzentrieren (Kinder, Haushalt).",
      "Man vermisst den Kontakt zu Kollegen – soziale Isolation.",
      "Die Grenze zwischen Arbeit und Freizeit verschwimmt.",
      "Nicht alle Jobs können im Homeoffice erledigt werden.",
    ],
    text: undefined,
  },
  {
    id: "flexi",
    label: "Flexible Arbeitszeiten",
    cat: "arbeit",
    pro: [
      "Flexible Arbeitszeiten sind ideal für Familien mit Kindern.",
      "Mitarbeiter arbeiten besser, wenn sie selbst entscheiden, wann sie produktiv sind.",
      "Man kann private Termine leichter wahrnehmen.",
    ],
    con: [
      "Feste Arbeitszeiten schaffen Ordnung und erleichtern die Teamarbeit.",
      "Bei flexiblen Zeiten kann es zu Kommunikationsproblemen im Team kommen.",
      "Manche Mitarbeiter können ihre Zeit nicht gut einteilen.",
    ],
    text: undefined,
  },
  {
    id: "teamarbeit",
    label: "Teamarbeit vs. Einzelarbeit",
    cat: "arbeit",
    pro: [
      "Teamarbeit steigert Motivation und Kreativität – man lernt voneinander.",
      "Im Team teilt man die Arbeit und löst Probleme schneller.",
      "Teamarbeit fördert soziale Kompetenzen.",
    ],
    con: [
      "Im Team kann es zu Konflikten kommen.",
      "Manche Mitarbeiter arbeiten allein effizienter.",
      "Aufgaben werden manchmal nicht gleichmäßig verteilt.",
    ],
    text: undefined,
  },
  {
    id: "rente",
    label: "Rentenalter erhöhen?",
    cat: "gesellschaft",
    pro: [
      "Die Bevölkerung wird älter – das Rentensystem braucht Reformen.",
      "Viele Menschen sind auch mit 67 noch fit und können arbeiten.",
      "Ohne Reformen kann das Rentensystem kollabieren.",
    ],
    con: [
      "Körperliche Arbeit ist mit 67 sehr anstrengend und gesundheitsschädlich.",
      "Ältere Arbeitnehmer blockieren Arbeitsplätze für junge Menschen.",
      "Man sollte nach einem langen Arbeitsleben Ruhe verdient haben.",
    ],
    text: undefined,
  },
  {
    id: "auswand",
    label: "Auswanderung",
    cat: "gesellschaft",
    pro: [
      "Neue Kulturen, Menschen und Bräuche kennenlernen.",
      "Bessere Lebensverhältnisse – bessere Arbeit, höheres Einkommen.",
      "Die Kinder bekommen eine bessere Bildung und Gesundheitsversorgung.",
    ],
    con: [
      "Man fühlt sich fremd und einsam.",
      "Es ist schwierig, sich an die neue Sprache und Kultur zu gewöhnen.",
      "Man hat Heimweh und ist weit von Familie und Freunden entfernt.",
    ],
    text: undefined,
  },
  {
    id: "multikulti",
    label: "Multikulturalität / Integration",
    cat: "gesellschaft",
    pro: [
      "Multikulturalität bereichert die Gesellschaft – neue Ideen, Kulturen und Küchen.",
      "Einwanderer übernehmen wichtige Berufe (Pflege, Handwerk, IT).",
      "Integration fördert gegenseitiges Verständnis und Toleranz.",
    ],
    con: [
      "Integration ist nicht immer einfach – Sprach- und Kulturbarrieren.",
      "Es kann zu sozialen Spannungen kommen, wenn zu viele Menschen gleichzeitig einwandern.",
      "Ohne ausreichende Sprachkenntnisse ist eine echte Integration schwierig.",
    ],
    text: undefined,
  },
  {
    id: "liebe2",
    label: "Dürfen Männer weinen?",
    cat: "gesellschaft",
    isTextOnly: true,
    text: "Männer sind auch Menschen – sie haben Gefühle und dürfen sie zeigen. Viele Menschen meinen, dass Weinen ein Zeichen von Schwäche ist. Aber viele Studien haben gezeigt, dass Weinen sehr nützlich und sogar gesund sein kann – für die Augen und die Nerven. Außerdem können Männer durch Weinen ihre Traurigkeit und ihr Mitgefühl zeigen. Deshalb bin ich der Meinung, dass Männer weinen dürfen. Aber nicht über Kleinigkeiten.",
  },
  {
    id: "ehrenamt",
    label: "Freiwillige / Ehrenamtliche Arbeit",
    cat: "gesellschaft",
    pro: [
      "Man kann Menschen aus aller Welt helfen – das ist ein gutes Gefühl.",
      "Es ist eine Chance, neue Kulturen und Lebensstile kennenzulernen.",
      "Man entdeckt eigene Fähigkeiten und Stärken.",
      "Freiwillige Arbeit verbessert den Lebenslauf.",
    ],
    con: [
      "Freiwillige Arbeit ist unbezahlt – man verliert Zeit für bezahlte Arbeit.",
      "Oft werden Freiwillige ausgenutzt.",
      "Nicht jeder hat die Zeit oder die Möglichkeit, freiwillig zu arbeiten.",
    ],
    text: undefined,
  },
  {
    id: "politik",
    label: "Jugendliche und Politik",
    cat: "gesellschaft",
    pro: [
      "Jugendliche sind die Zukunft – sie sollten an politischen Entscheidungen beteiligt sein.",
      "Das Wahlalter auf 16 zu senken würde das politische Interesse fördern.",
      "Politik betrifft auch das Leben der Jugendlichen direkt.",
    ],
    con: [
      "Viele Jugendliche sind noch nicht reif genug für politische Entscheidungen.",
      "Jugendliche haben wenig Lebenserfahrung.",
      "Schule und Eltern sollten zuerst politische Bildung vermitteln.",
    ],
    text: undefined,
  },
  {
    id: "umwelt",
    label: "Umweltschutz / Klimawandel",
    cat: "umwelt",
    pro: [
      "Der Klimawandel ist eine der größten Bedrohungen unserer Zeit.",
      "Jeder Mensch kann durch sein Verhalten die Umwelt schützen: Recycling, weniger Autofahren, Energie sparen.",
      "Ohne Umweltschutz hinterlassen wir unseren Kindern eine zerstörte Erde.",
    ],
    con: [
      "Umweltschutzmaßnahmen kosten viel Geld und gefährden Arbeitsplätze.",
      "Viele Menschen können sich umweltfreundliche Produkte nicht leisten.",
      "Ohne internationale Zusammenarbeit bringen nationale Maßnahmen wenig.",
    ],
    text: undefined,
  },
  {
    id: "plastik",
    label: "Plastiktüten verbieten?",
    cat: "umwelt",
    pro: [
      "Plastiktüten verschmutzen Meere und Natur – Millionen Tiere sterben daran.",
      "Papiertüten und Stoffbeutel sind umweltfreundlichere Alternativen.",
      "Ein Verbot würde das Bewusstsein für Umweltschutz stärken.",
    ],
    con: [
      "Plastiktüten sind praktisch, günstig und wasserdicht.",
      "Papiertüten verbrauchen auch viele Ressourcen bei der Herstellung.",
      "Ein Verbot allein löst das Müllproblem nicht.",
    ],
    text: undefined,
  },
  {
    id: "strom",
    label: "Erneuerbare Energien / Strom sparen",
    cat: "umwelt",
    pro: [
      "Erneuerbare Energien (Solar, Wind) schützen die Umwelt und sind langfristig günstiger.",
      "Strom sparen reduziert den CO₂-Ausstoß und spart Geld.",
      "Die Abhängigkeit von fossilen Brennstoffen wird reduziert.",
    ],
    con: [
      "Der Ausbau erneuerbarer Energien kostet viel Geld.",
      "Solar- und Windenergie sind wetterabhängig – nicht immer zuverlässig.",
      "Nicht jeder kann sich eine Solaranlage leisten.",
    ],
    text: undefined,
  },
  {
    id: "elektroauto",
    label: "Elektroautos",
    cat: "umwelt",
    pro: [
      "Elektroautos verursachen keine direkten Abgase – gut für die Luft in Städten.",
      "Langfristig sind sie günstiger im Betrieb.",
      "Sie sind leiser und komfortabler als Benzinmotoren.",
    ],
    con: [
      "Elektroautos sind sehr teuer zu kaufen.",
      "Die Reichweite ist begrenzt und es gibt zu wenige Ladestationen.",
      "Die Batterien werden aus seltenen Rohstoffen hergestellt – nicht immer umweltfreundlich.",
    ],
    text: undefined,
  },
  {
    id: "radfahren",
    label: "Fahrrad vs. Auto in der Stadt",
    cat: "umwelt",
    pro: [
      "Fahrrad fahren ist gesund, umweltfreundlich und spart Geld.",
      "In der Stadt ist das Fahrrad oft schneller als das Auto.",
      "Keine Parkplatzsuche und keine Stauprobleme.",
    ],
    con: [
      "Bei schlechtem Wetter ist Fahrradfahren unangenehm.",
      "Mit dem Fahrrad kann man keine schweren Einkäufe transportieren.",
      "Nicht alle Städte haben gute Fahrradwege.",
    ],
    text: undefined,
  },
  {
    id: "stadtauto",
    label: "Stadtzentrum ohne Autos",
    cat: "umwelt",
    pro: [
      "Stadtteile ohne Autos sind ruhiger, sauberer und umweltfreundlicher.",
      "Kinder und Fußgänger haben mehr Sicherheit.",
      "Man spart viel Platz, der sonst für Parkplätze gebraucht wird.",
    ],
    con: [
      "Man braucht mehr Zeit für öffentliche Verkehrsmittel.",
      "Ältere Menschen und Familien mit Kindern müssen länger laufen.",
      "Ein autofreies Stadtzentrum ist nicht gut für Geschäfte und Lieferungen.",
    ],
    text: undefined,
  },
  {
    id: "oeffentlich",
    label: "Öffentliche Verkehrsmittel vs. Auto",
    cat: "umwelt",
    pro: [
      "Öffentliche Verkehrsmittel sind umweltfreundlicher und günstiger.",
      "Man kann während der Fahrt lesen, arbeiten oder schlafen.",
      "Kein Stress durch Stau oder Parkplatzsuche.",
    ],
    con: [
      "Öffentliche Verkehrsmittel sind oft unpünktlich und überfüllt.",
      "Auf dem Land gibt es oft keine guten Verbindungen.",
      "Mit dem Auto ist man flexibler und schneller, besonders auf dem Land.",
    ],
    text: undefined,
  },
  {
    id: "stadtland",
    label: "Leben in der Stadt oder auf dem Land",
    cat: "gesellschaft",
    pro: [
      "Stadt: Großes Jobangebot, viele Krankenhäuser, Schulen, Verkehrsmittel, aktives Leben.",
      "Land: Viel Natur, frische Luft, frisches Essen, gastfreundliche Menschen, günstiges Leben.",
    ],
    con: [
      "Stadt: Viel Lärm, Stress, Stau, teure Mieten, Kriminalität.",
      "Land: Langweilig, keine Krankenhäuser, Schulen oder Einkaufsmöglichkeiten in der Nähe.",
    ],
    text: undefined,
  },
  {
    id: "urlaub",
    label: "Verreisen oder zu Hause bleiben?",
    cat: "freizeit",
    pro: [
      "Verreisen: Neue Kulturen, Orte und Menschen kennenlernen – hilft, Stress zu vergessen.",
      "Verreisen macht offen und weltgewandt.",
      "Zu Hause bleiben: Geld sparen, andere Hobbys machen, entspannen.",
    ],
    con: [
      "Verreisen: Kostet Geld und Kraft. Durch Klimawechsel kann man krank werden.",
      "Zu Hause bleiben: Langweilig – man bleibt im Alltag stecken.",
    ],
    text: undefined,
  },
  {
    id: "strand",
    label: "Urlaub am Strand",
    cat: "freizeit",
    pro: [
      "Am Strand kann man sich erholen, entspannen und den Alltag vergessen.",
      "Die Sonne und das Wasser geben positive Energie.",
      "Man kann aktiv sein: Beachvolleyball, Schwimmen, Surfen.",
    ],
    con: [
      "Urlaub am Strand macht manchmal passiv und faul.",
      "Zu viel Sonne ist schädlich für die Haut.",
      "Man lernt wenig über andere Kulturen und Orte.",
    ],
    text: undefined,
  },
  {
    id: "fernsehen",
    label: "Kinder and Television",
    cat: "freizeit",
    pro: [
      "Im Fernsehen kann man viele nützliche Sendungen sehen (Natur, Geschichte, Sprachen).",
      "Zeichentrickfilme können die Fantasie der Kinder entwickeln.",
      "Das Fernsehen ist ein Fenster auf die Welt.",
    ],
    con: [
      "Zu viel Fernsehen macht Kinder faul und passiv.",
      "Kinder sollten sich mehr bewegen und mit anderen Kindern spielen.",
      "Es gibt viele Sendungen, die für Kinder nicht geeignet sind.",
    ],
    text: undefined,
  },
  {
    id: "musik",
    label: "Müssen Kinder ein Musikinstrument lernen?",
    cat: "freizeit",
    pro: [
      "Musik entwickelt die Intelligenz und Konzentration des Kindes.",
      "Kinder können dadurch ihre Freizeit sinnvoll nutzen.",
      "Musik fördert Kreativität und Geduld.",
    ],
    con: [
      "Musiklernen kann teuer sein (Instrument, Unterricht).",
      "Es kostet viel Zeit und Mühe.",
      "Kinder sollten frei wählen können, welches Hobby sie mögen.",
    ],
    text: undefined,
  },
  {
    id: "freizeit2",
    label: "Sollten Kinder ihre Freizeit planen?",
    cat: "freizeit",
    pro: [
      "Wenn Kinder ihre Freizeit planen, lernen sie Selbstständigkeit und Verantwortung.",
      "Sie werden ordentlicher und pünktlicher.",
      "Strukturierte Freizeit verhindert, dass Kinder stundenlang Videospiele spielen.",
    ],
    con: [
      "Kinder brauchen auch Spontanität und unstrukturierte Spielzeit.",
      "Zu viel Planung macht Kinder unsicher und gestresst.",
      "Kinder sind keine Roboter – sie brauchen Freiheit.",
    ],
    text: undefined,
  },
  {
    id: "unterricht",
    label: "Gemischter oder getrennter Unterricht?",
    cat: "bildung",
    pro: [
      "Gemischter Unterricht bereitet auf das echte Leben vor – im Leben ist alles gemischt.",
      "Er erhöht den gesunden Wettbewerb zwischen Mädchen und Jungen.",
      "Beide Geschlechter lernen, ohne Hemmungen miteinander zu kommunizieren.",
    ],
    con: [
      "Manche Schüler schämen sich vor dem anderen Geschlecht.",
      "Getrennter Unterricht fördert schüchterne Schüler und verbessert die Leistung.",
      "Unterschiedliche Lernstile von Mädchen und Jungen werden besser berücksichtigt.",
    ],
    text: undefined,
  },
  {
    id: "einkz",
    label: "Brauchen wir Einkaufszentren?",
    cat: "gesellschaft",
    pro: [
      "Im Einkaufszentrum hat man viele Möglichkeiten an einem Ort.",
      "Man kann bei jedem Wetter einkaufen.",
      "Es gibt Freizeitmöglichkeiten: Restaurants, Kinos, Spielplätze.",
      "Einkaufszentren schaffen viele Arbeitsplätze.",
    ],
    con: [
      "Einkaufszentren liegen oft am Stadtrand – man muss lange fahren.",
      "Sie sind immer voll – lange Schlangen an der Kasse.",
      "Man gibt viel Geld aus.",
      "Sie verdrängen kleine lokale Geschäfte.",
    ],
    text: undefined,
  },
  {
    id: "rauch",
    label: "Rauchverbot im Restaurant?",
    cat: "gesundheit",
    pro: [
      "Raucher schaden nicht nur sich selbst, sondern auch anderen Gästen durch Passivrauchen.",
      "Restaurants sind öffentliche Plätze mit Kindern und schwangeren Frauen.",
      "Das Essen schmeckt besser ohne Rauch.",
    ],
    con: [
      "Rauchern sollte die Freiheit gelassen werden, in öffentlichen Räumen zu rauchen.",
      "Ein Rauchverbot kann Kunden vertreiben.",
      "Rauchen ist ein legales Produkt.",
    ],
    text: undefined,
  },
  {
    id: "stress",
    label: "Stress im Alltag / Work-Life-Balance",
    cat: "arbeit",
    pro: [
      "Eine gute Work-Life-Balance ist wichtig für die Gesundheit.",
      "Regelmäßige Pausen und Freizeitaktivitäten reduzieren Stress.",
      "Entspannte Mitarbeiter sind produktiver und kreativer.",
    ],
    con: [
      "In der modernen Welt ist es schwierig, Arbeit und Privatleben zu trennen.",
      "Viele Menschen definieren sich durch ihre Arbeit und wollen viel arbeiten.",
      "Wirtschaftlicher Druck zwingt viele Menschen zur Überstunden.",
    ],
    text: undefined,
  },
  {
    id: "krippe",
    label: "Kinder früh in die Krippe?",
    cat: "gesellschaft",
    pro: [
      "In der Krippe lernen Kinder früh soziale Kompetenzen und Teamarbeit.",
      "Eltern können früher arbeiten gehen und die Karriere fortführen.",
      "Professionelle Betreuung fördert die Entwicklung des Kindes.",
    ],
    con: [
      "Kleine Kinder brauchen vor allem die Nähe der Eltern.",
      "Krippen können teuer sein.",
      "Manche Eltern haben ein schlechtes Gewissen, das Kind früh abzugeben.",
    ],
    text: undefined,
  },
  {
    id: "jugendlich",
    label: "Haben Kinder zu viel / zu wenig Freizeit?",
    cat: "freizeit",
    pro: [
      "In der Schule haben Kinder viele Fächer und der Stundenplan ist voll.",
      "Kinder haben immer viele Hausaufgaben und müssen zu Hause helfen.",
    ],
    con: [
      "Kinder brauchen Freizeit zum Spielen, Basteln und Ausruhen.",
      "Kinder brauchen mehr Bewegung und Kontakt mit anderen Kindern.",
    ],
    text: undefined,
  },
  {
    id: "freund",
    label: "Freundschaft",
    cat: "gesellschaft",
    pro: [
      "Freunde unterstützen uns in schwierigen Zeiten.",
      "Freundschaft macht das Leben glücklicher und weniger einsam.",
      "Man kann mit Freunden Hobbys teilen und Spaß haben.",
    ],
    con: [
      "Freundschaften brauchen viel Zeit und Pflege.",
      "Es kann zu Enttäuschungen oder Streit kommen.",
      "Manchmal ist es schwierig, echte Freunde zu finden.",
    ],
  },
  {
    id: "heirat",
    label: "Heiraten",
    cat: "gesellschaft",
    pro: [
      "Die Ehe bietet Sicherheit und Stabilität für die Familie.",
      "Man zeigt seine Liebe und Verbundenheit offiziell.",
      "Es gibt rechtliche und steuerliche Vorteile.",
    ],
    con: [
      "Eine Hochzeit ist oft sehr teuer und stressig.",
      "Man verliert ein Stück seiner Unabhängigkeit.",
      "Viele Ehen enden leider in einer Scheidung.",
    ],
  },
  {
    id: "video",
    label: "Videospiele",
    cat: "freizeit",
    pro: [
      "Videospiele fördern die Konzentration und das strategische Denken.",
      "Man kann online mit Freunden spielen und neue Leute kennenlernen.",
      "Es ist eine gute Möglichkeit, sich nach der Arbeit zu entspannen.",
    ],
    con: [
      "Zu viel Spielen kann süchtig machen und die Gesundheit schaden.",
      "Man vernachlässigt oft soziale Kontakte im echten Leben.",
      "Einige Spiele sind sehr gewalttätig und für Kinder nicht geeignet.",
    ],
  },
  {
    id: "reise",
    label: "Reisen",
    cat: "freizeit",
    pro: [
      "Man entdeckt neue Kulturen, Sprachen und Lebensweisen.",
      "Reisen erweitert den Horizont und macht offener.",
      "Man kann sich vom Alltagsstress erholen und neue Energie tanken.",
    ],
    con: [
      "Reisen ist oft teuer (Flug, Hotel, Verpflegung).",
      "Massentourismus schadet der Umwelt und dem Klima.",
      "Man kann Heimweh bekommen oder Probleme im Ausland haben.",
    ],
  },
];
